In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import env
import eval_model
import wrangle3


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')


pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option('display.float_format', lambda x: '%.5f' % x)



import gmaps
import gmaps.datasets

gmaps.configure(api_key="AIzaSyDlW6BYId6BmIp-mmA_lY_xNiQOKabd-2Q")


#Modeling Tools
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import statsmodels.api as sm
from statsmodels.formula.api import ols

from datetime import date
from scipy import stats


## Evaluation tools
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from math import sqrt

In [13]:
train, X_train, y_train, X_validate, y_validate, X_test, y_test=wrangle3.wrangle()

In [3]:
X_train.head()

,Unnamed: 0,parcelid,bathroomcnt,bedroomcnt,calculatedfinishedsquarefeet,fips,latitude,longitude,lotsizesquarefeet,regionidcity,regionidcounty,regionidzip,yearbuilt,structuretaxvaluedollarcnt,taxvaluedollarcnt,landtaxvaluedollarcnt,taxamount,county,age,age_bin,taxrate,acres,acres_bin,sqft_bin,structure_dollar_per_sqft,structure_dollar_sqft_bin,land_dollar_per_sqft,lot_dollar_sqft_bin,bath_bed_ratio,cola,logerror_bins,baseline,scaled_latitude,scaled_longitude,scaled_bathroomcnt,scaled_taxrate,scaled_bedroomcnt,scaled_lotsizesquarefeet,scaled_age,scaled_acres,scaled_bath_bed_ratio,scaled_calculatedfinishedsquarefeet,area_cluster,size_cluster,price_cluster,area_cluster_la_newer,area_cluster_la_older,area_cluster_northwest_costal,area_cluster_palmdale_landcaster,area_cluster_santa_clarita,area_cluster_se_coast,size_cluster_a,size_cluster_b,size_cluster_c,size_cluster_d,size_cluster_e,size_cluster_f,size_cluster_g,price_cluster_a,price_cluster_b,price_cluster_c,price_cluster_d,price_cluster_e
21580,21580,11204960,3.00000,4.00000,2000.00000,6037.00000,34.56170,-118.08275,6999.00000,40227.00000,3101.00000,97328.00000,1987.00000,104877.00000,131090.00000,26213.00000,2623.93000,Los_Angeles,30.00000,0.20000,2.00162,0.16067,0.20000,0.40000,52.43850,0.20000,3.74525,0.10000,0.75000,0,"(-0.05, 0.05]",0.01791,0.82963,0.73177,0.33333,0.20338,0.50000,0.00883,0.21324,0.00883,0.19643,0.17285,palmdale_landcaster,f,c,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0
32781,32781,14323862,6.00000,6.00000,7393.00000,6059.00000,33.60152,-117.84523,24000.00000,40009.00000,1286.00000,96975.00000,1995.00000,1556016.00000,2449943.00000,893927.00000,29921.84000,Orange,22.00000,0.20000,1.22133,0.55096,0.40000,0.90000,210.47153,0.60000,37.24696,0.30000,1.00000,0,"(0.05, 0.2]",0.01791,0.17714,0.85659,0.83333,0.12372,0.83333,0.03101,0.15441,0.03101,0.28571,0.74125,se_coast,d,a,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0
33161,33161,12205584,2.00000,3.00000,1778.00000,6037.00000,33.96600,-118.29863,4948.00000,12447.00000,3101.00000,96025.00000,1936.00000,87000.00000,347000.00000,260000.00000,4248.21000,Los_Angeles,81.00000,0.60000,1.22427,0.11359,0.10000,0.40000,48.93138,0.10000,52.54648,0.40000,0.66667,1,"(-0.05, 0.05]",0.01791,0.42483,0.61833,0.16667,0.12402,0.33333,0.00615,0.58824,0.00615,0.16667,0.14945,la_older,b,d,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
45785,45785,12078527,3.00000,4.00000,2777.00000,6037.00000,34.16601,-118.21853,9989.00000,45457.00000,3101.00000,96327.00000,1990.00000,322342.00000,875355.00000,553013.00000,9603.39000,Los_Angeles,27.00000,0.20000,1.09709,0.22932,0.20000,0.60000,116.07562,0.40000,55.36220,0.40000,0.75000,0,"(0.05, 0.2]",0.01791,0.56074,0.66042,0.33333,0.11104,0.50000,0.01273,0.19118,0.01273,0.19643,0.25474,santa_clarita,f,a,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0
45820,45820,14266520,3.00000,4.00000,1939.00000,6059.00000,33.70670,-117.89868,6028.00000,47568.00000,1286.00000,97004.00000,1971.00000,139321.00000,327623.00000,188302.00000,3923.98000,Orange,46.00000,0.33300,1.19771,0.13838,0.10000,0.40000,71.85199,0.20000,31.23789,0.30000,0.75000,0,"(-0.05, 0.05]",0.01791,0.24862,0.82851,0.33333,0.12131,0.50000,0.00756,0.33088,0.00756,0.19643,0.16642,se_coast,f,d,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0

In [14]:
train2 = X_train

In [16]:
train2['log_error']=y_train

In [17]:
train2.sample(50)

,Unnamed: 0,parcelid,bathroomcnt,bedroomcnt,calculatedfinishedsquarefeet,fips,latitude,longitude,lotsizesquarefeet,regionidcity,regionidcounty,regionidzip,yearbuilt,structuretaxvaluedollarcnt,taxvaluedollarcnt,landtaxvaluedollarcnt,taxamount,county,age,age_bin,taxrate,acres,acres_bin,sqft_bin,structure_dollar_per_sqft,structure_dollar_sqft_bin,land_dollar_per_sqft,lot_dollar_sqft_bin,bath_bed_ratio,cola,logerror_bins,baseline,scaled_latitude,scaled_longitude,scaled_bathroomcnt,scaled_taxrate,scaled_bedroomcnt,scaled_lotsizesquarefeet,scaled_age,scaled_acres,scaled_bath_bed_ratio,scaled_calculatedfinishedsquarefeet,area_cluster,size_cluster,price_cluster,area_cluster_la_newer,area_cluster_la_older,area_cluster_northwest_costal,area_cluster_palmdale_landcaster,area_cluster_santa_clarita,area_cluster_se_coast,size_cluster_a,size_cluster_b,size_cluster_c,size_cluster_d,size_cluster_e,size_cluster_f,size_cluster_g,price_cluster_a,price_cluster_b,price_cluster_c,price_cluster_d,price_cluster_e,log_error
36936,36936,14153047,2.50000,3.00000,1934.00000,6059.00000,33.93649,-117.91799,7131.00000,17150.00000,1286.00000,97035.00000,1961.00000,144244.00000,251559.00000,107315.00000,3195.20000,Orange,56.00000,0.40000,1.27016,0.16371,0.20000,0.40000,74.58325,0.20000,15.04908,0.20000,0.83333,0,"(-0.05, 0.05]",0.01791,0.40477,0.81836,0.25000,0.12871,0.33333,0.00900,0.40441,0.00900,0.22619,0.16589,la_newer,a,d,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0.00163
18284,18284,13024542,1.00000,3.00000,1352.00000,6037.00000,34.11805,-117.89444,6205.00000,37015.00000,3101.00000,96464.00000,1955.00000,97165.00000,184138.00000,86973.00000,2436.71000,Los_Angeles,62.00000,0.46600,1.32331,0.14245,0.10000,0.30000,71.86760,0.20000,14.01660,0.20000,0.33333,0,"(-0.05, 0.05]",0.01791,0.52815,0.83073,0.00000,0.13413,0.33333,0.00779,0.44853,0.00779,0.04762,0.10455,la_newer,g,d,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0.04552
21453,21453,12303159,1.00000,2.00000,860.00000,6037.00000,33.93819,-118.21675,4712.00000,47762.00000,3101.00000,96125.00000,1942.00000,46138.00000,116922.00000,70784.00000,1796.92000,Los_Angeles,75.00000,0.53300,1.53685,0.10817,0.10000,0.10000,53.64884,0.20000,15.02207,0.20000,0.50000,0,"(-0.2, -0.05]",0.01791,0.40593,0.66136,0.00000,0.15593,0.16667,0.00584,0.54412,0.00584,0.10714,0.05270,la_older,g,c,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,-0.08560
34940,34940,10962967,2.00000,3.00000,1734.00000,6037.00000,34.31856,-118.45709,11000.00000,12447.00000,3101.00000,96368.00000,1974.00000,195501.00000,391623.00000,196122.00000,4858.78000,Los_Angeles,43.00000,0.33300,1.24068,0.25253,0.30000,0.40000,112.74567,0.40000,17.82927,0.20000,0.66667,1,"(-0.05, 0.05]",0.01791,0.66441,0.53506,0.16667,0.12570,0.33333,0.01405,0.30882,0.01405,0.16667,0.14481,santa_clarita,b,a,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,-0.02315
2041,2041,12884428,1.00000,2.00000,816.00000,6037.00000,34.05069,-117.75391,5969.00000,20008.00000,3101.00000,96506.00000,1948.00000,18404.00000,28315.00000,9911.00000,524.30000,Los_Angeles,69.00000,0.46600,1.85167,0.13703,0.10000,0.10000,22.55392,0.00000,1.66041,0.10000,0.50000,0,"(-0.05, 0.05]",0.01791,0.48238,0.90458,0.00000,0.18807,0.16667,0.00748,0.50000,0.00748,0.10714,0.04806,la_newer,g,c,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,-0.03210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4879,4879,10837764,2.00000,3.00000,1132.00000,6037.00000,34.19076,-118.47698,5999.00000,12447.00000,3101.00000,96415.00000,1950.00000,106831.00000,292303.00000,185472.00000,3612.25000,Los_Angeles,67.00000,0.46600,1.23579,0.13772,0.10000,0.20000,94.37367,0.30000,30.91715,0.30000,0.66667,1,"(-0.05, 0.05]",0.01791,0.57756,0.52461,0.16667,0.12520,0.33333,0.00752,0.48529,0.00752,0.16667,0.08137,santa_clarita,b,a,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,-0.00373
11315,11315,11028919,1.00000,4.00000,1067.00000,6037.00000,34.23613,-118.39255,24853.00000,12447.00000,3101.00000,96375.00000,1947.00000,75849.00000,305852.00000,230003.00000,3856.94000,Los_Angeles,70.00000,0.46600,1.26105,0.57055,0.40000,0.20000,71.08622,0.20000,9.25454,0.20000,0.25000,1,"(-5.0, -0.2]",0.01791,0.60839,0.56898,0.00000,0.12778,0.50000,0.03212,0.50735,0.03212,0.01786,0.07452,santa_clarita,g,d,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,-0.28681
17973,17973,11640734,4.00000,4.00000,3714.00000,6037.00000,34.10051,-118.42038,25864.00000,12447.00000,3101.00000,96086.00000,1983.00000,995959.00000,2489898.00000,1493939.00000,30051.35000,Los_Angeles,34.00000,0.26600,1.20693,0.59376,0.40000,0.70000,268.16344,0.60000,57.76133,0.40000,1.00000,1,"(0.05, 0.2]",0.01791,0.51623,0.55435,0.50000,0.12225,0.50000,0.03344,0.24265,0.03344,0.28571,0.35350,santa_clarita,d,a,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0.05727
18707,18707,11450050,2.00000,3.00000,1427.00000,6037.00000,33.87629,-118.32879,6865.00000,54722.00000,3101.00000,96162.00000,1948.00000,194018.00000,404210.00000,210192.00000,4709.16000,Los_Angeles,69.00000,0.46600,1.16503,0.15760,0.20000,0.30000,135.96216,0.40000,30.61792,0.30000,0.66667,0,"(-0.05, 0.05]",0.01791,0.36386,0.60248,0.16667,0.11798,0.33333,0.00865,0.50000,0.00865,0.16667,0.11246,la_older,b,a,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,-0.00653
42348,42348,11962930,2.00000,3.00000,1160.00000,6037.00000,34.11378,-118.22313,4583.00000,12447.00000,3101.00000,96046.00000,1941.00000,164846.00000,619945.00000,455099.00000,7505.87000,Los_Angeles,76.00000,0.53300,1.21073,0.10521,0.10000,0.20000,142.10862,0.40000,99.30155,0.40000,0.66667,1,"(-0.05, 0.05]",0.01791,0.52525,0.65800,0.16667,0.12264,0.33333,0.00567,0.55147,0.00567,0.16667,0.08432,la_older,b,a,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,-0.00153

In [18]:
train=train2

## Make ols model with clusters as features

In [19]:
train.dtypes

Unnamed: 0                                int64
parcelid                                  int64
bathroomcnt                             float64
bedroomcnt                              float64
calculatedfinishedsquarefeet            float64
fips                                    float64
latitude                                float64
longitude                               float64
lotsizesquarefeet                       float64
regionidcity                            float64
regionidcounty                          float64
regionidzip                             float64
yearbuilt                               float64
structuretaxvaluedollarcnt              float64
taxvaluedollarcnt                       float64
landtaxvaluedollarcnt                   float64
taxamount                               float64
county                                   object
age                                     float64
age_bin                                 float64
taxrate                                 float64
acres                                   float64
acres_bin                               float64
sqft_bin                                float64
structure_dollar_per_sqft               float64
structure_dollar_sqft_bin               float64
land_dollar_per_sqft                    float64
lot_dollar_sqft_bin                     float64
bath_bed_ratio                          float64
cola                                      int64
logerror_bins                          category
baseline                                float64
scaled_latitude                         float64
scaled_longitude                        float64
scaled_bathroomcnt                      float64
scaled_taxrate                          float64
scaled_bedroomcnt                       float64
scaled_lotsizesquarefeet                float64
scaled_age                              float64
scaled_acres                            float64
scaled_bath_bed_ratio                   float64
scaled_calculatedfinishedsquarefeet     float64
area_cluster                             object
size_cluster                             object
price_cluster                            object
area_cluster_la_newer                     uint8
area_cluster_la_older                     uint8
area_cluster_northwest_costal             uint8
area_cluster_palmdale_landcaster          uint8
area_cluster_santa_clarita                uint8
area_cluster_se_coast                     uint8
size_cluster_a                            uint8
size_cluster_b                            uint8
size_cluster_c                            uint8
size_cluster_d                            uint8
size_cluster_e                            uint8
size_cluster_f                            uint8
size_cluster_g                            uint8
price_cluster_a                           uint8
price_cluster_b                           uint8
price_cluster_c                           uint8
price_cluster_d                           uint8
price_cluster_e                           uint8
log_error                               float64
dtype: object

AttributeError: module 'pandas' has no attribute 'df'

In [33]:
train.head()

,Unnamed: 0,parcelid,bathroomcnt,bedroomcnt,calculatedfinishedsquarefeet,fips,latitude,longitude,lotsizesquarefeet,regionidcity,regionidcounty,regionidzip,yearbuilt,structuretaxvaluedollarcnt,taxvaluedollarcnt,landtaxvaluedollarcnt,taxamount,county,age,age_bin,taxrate,acres,acres_bin,sqft_bin,structure_dollar_per_sqft,structure_dollar_sqft_bin,land_dollar_per_sqft,lot_dollar_sqft_bin,bath_bed_ratio,cola,logerror_bins,baseline,scaled_latitude,scaled_longitude,scaled_bathroomcnt,scaled_taxrate,scaled_bedroomcnt,scaled_lotsizesquarefeet,scaled_age,scaled_acres,scaled_bath_bed_ratio,scaled_calculatedfinishedsquarefeet,area_cluster,size_cluster,price_cluster,area_cluster_la_newer,area_cluster_la_older,area_cluster_northwest_costal,area_cluster_palmdale_landcaster,area_cluster_santa_clarita,area_cluster_se_coast,size_cluster_a,size_cluster_b,size_cluster_c,size_cluster_d,size_cluster_e,size_cluster_f,size_cluster_g,price_cluster_a,price_cluster_b,price_cluster_c,price_cluster_d,price_cluster_e,log_error,mvp_prdictions
21580,21580,11204960,3.00000,4.00000,2000.00000,6037.00000,34.56170,-118.08275,6999.00000,40227.00000,3101.00000,97328.00000,1987.00000,104877.00000,131090.00000,26213.00000,2623.93000,Los_Angeles,30.00000,0.20000,2.00162,0.16067,0.20000,0.40000,52.43850,0.20000,3.74525,0.10000,0.75000,0,"(-0.05, 0.05]",0.01791,0.82963,0.73177,0.33333,0.20338,0.50000,0.00883,0.21324,0.00883,0.19643,0.17285,palmdale_landcaster,f,c,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,-0.01503,0.01352
32781,32781,14323862,6.00000,6.00000,7393.00000,6059.00000,33.60152,-117.84523,24000.00000,40009.00000,1286.00000,96975.00000,1995.00000,1556016.00000,2449943.00000,893927.00000,29921.84000,Orange,22.00000,0.20000,1.22133,0.55096,0.40000,0.90000,210.47153,0.60000,37.24696,0.30000,1.00000,0,"(0.05, 0.2]",0.01791,0.17714,0.85659,0.83333,0.12372,0.83333,0.03101,0.15441,0.03101,0.28571,0.74125,se_coast,d,a,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0.15846,0.03573
33161,33161,12205584,2.00000,3.00000,1778.00000,6037.00000,33.96600,-118.29863,4948.00000,12447.00000,3101.00000,96025.00000,1936.00000,87000.00000,347000.00000,260000.00000,4248.21000,Los_Angeles,81.00000,0.60000,1.22427,0.11359,0.10000,0.40000,48.93138,0.10000,52.54648,0.40000,0.66667,1,"(-0.05, 0.05]",0.01791,0.42483,0.61833,0.16667,0.12402,0.33333,0.00615,0.58824,0.00615,0.16667,0.14945,la_older,b,d,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,-0.01774,0.01181
45785,45785,12078527,3.00000,4.00000,2777.00000,6037.00000,34.16601,-118.21853,9989.00000,45457.00000,3101.00000,96327.00000,1990.00000,322342.00000,875355.00000,553013.00000,9603.39000,Los_Angeles,27.00000,0.20000,1.09709,0.22932,0.20000,0.60000,116.07562,0.40000,55.36220,0.40000,0.75000,0,"(0.05, 0.2]",0.01791,0.56074,0.66042,0.33333,0.11104,0.50000,0.01273,0.19118,0.01273,0.19643,0.25474,santa_clarita,f,a,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0.06685,0.01187
45820,45820,14266520,3.00000,4.00000,1939.00000,6059.00000,33.70670,-117.89868,6028.00000,47568.00000,1286.00000,97004.00000,1971.00000,139321.00000,327623.00000,188302.00000,3923.98000,Orange,46.00000,0.33300,1.19771,0.13838,0.10000,0.40000,71.85199,0.20000,31.23789,0.30000,0.75000,0,"(-0.05, 0.05]",0.01791,0.24862,0.82851,0.33333,0.12131,0.50000,0.00756,0.33088,0.00756,0.19643,0.16642,se_coast,f,d,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,-0.02213,0.04110

In [32]:
# Create Model
ols_model1 = ols(formula='log_error ~ area_cluster_la_newer + area_cluster_la_older + area_cluster_northwest_costal + area_cluster_palmdale_landcaster + area_cluster_santa_clarita + area_cluster_se_coast + size_cluster_a + size_cluster_b + size_cluster_c + size_cluster_d + size_cluster_e + size_cluster_f + size_cluster_g + price_cluster_a + price_cluster_b + price_cluster_c + price_cluster_d + price_cluster_e', data=train).fit()

# Make predictions
ols_yhat = ols_model1.predict(X_train)
X_train['mvp_prdictions']=ols_yhat

In [27]:

#  DataFrame for evaluating model 
ols_eval = y_train.copy()
validate_eval = y_validate.copy()
ols_eval = pd.DataFrame(ols_eval)
validate_eval = pd.DataFrame(validate_eval)
ols_eval.rename(columns={'logerror': 'actual'}, inplace=True)
validate_eval.rename(columns={'logerror': 'actual'}, inplace=True)

In [28]:
ols_eval

        actual
21580 -0.01503
32781  0.15846
33161 -0.01774
45785  0.06685
45820 -0.02213
...        ...
14404  0.03122
1276   0.09111
34315 -0.01855
24599  0.18463
14306 -0.02481

[36384 rows x 1 columns]

In [48]:

# Add baseline - median home value
ols_eval['baseline_yhat'] = ols_eval['actual'].mean()
validate_eval['baseline_yhat'] = ols_eval['actual'].mean()

In [49]:
ols_eval

        actual  baseline_yhat  ols_yhat  residuals
21580 -0.01503        0.01791   0.01352    0.02856
32781  0.15846        0.01791   0.03573   -0.12272
33161 -0.01774        0.01791   0.01181    0.02954
45785  0.06685        0.01791   0.01187   -0.05497
45820 -0.02213        0.01791   0.04110    0.06324
...        ...            ...       ...        ...
14404  0.03122        0.01791   0.04110    0.00988
1276   0.09111        0.01791   0.01591   -0.07520
34315 -0.01855        0.01791   0.01097    0.02952
24599  0.18463        0.01791   0.02338   -0.16125
14306 -0.02481        0.01791   0.01507    0.03988

[36384 rows x 4 columns]

In [50]:

# Add model prediction
ols_eval['ols_yhat'] = ols_model1.predict(X_train)

In [51]:
ols_eval

        actual  baseline_yhat  ols_yhat  residuals
21580 -0.01503        0.01791   0.01352    0.02856
32781  0.15846        0.01791   0.03573   -0.12272
33161 -0.01774        0.01791   0.01181    0.02954
45785  0.06685        0.01791   0.01187   -0.05497
45820 -0.02213        0.01791   0.04110    0.06324
...        ...            ...       ...        ...
14404  0.03122        0.01791   0.04110    0.00988
1276   0.09111        0.01791   0.01591   -0.07520
34315 -0.01855        0.01791   0.01097    0.02952
24599  0.18463        0.01791   0.02338   -0.16125
14306 -0.02481        0.01791   0.01507    0.03988

[36384 rows x 4 columns]

-[] Wranlge need to add clusters and encoding to x_validate

In [36]:
X_validate.head()

,Unnamed: 0,parcelid,bathroomcnt,bedroomcnt,calculatedfinishedsquarefeet,fips,latitude,longitude,lotsizesquarefeet,regionidcity,regionidcounty,regionidzip,yearbuilt,structuretaxvaluedollarcnt,taxvaluedollarcnt,landtaxvaluedollarcnt,taxamount,county,age,age_bin,taxrate,acres,acres_bin,sqft_bin,structure_dollar_per_sqft,structure_dollar_sqft_bin,land_dollar_per_sqft,lot_dollar_sqft_bin,bath_bed_ratio,cola,baseline,scaled_latitude,scaled_longitude,scaled_bathroomcnt,scaled_taxrate,scaled_bedroomcnt,scaled_lotsizesquarefeet,scaled_age,scaled_acres,scaled_bath_bed_ratio,scaled_calculatedfinishedsquarefeet,area_cluster,size_cluster,price_cluster
20430,20430,11304460,3.00000,4.00000,2334.00000,6037.00000,34.68774,-118.18418,6631.00000,5534.00000,3101.00000,97319.00000,1990.00000,173161.00000,216450.00000,43289.00000,3463.67000,Los_Angeles,27.00000,0.20000,1.60022,0.15223,0.20000,0.50000,74.19066,0.20000,6.52828,0.20000,0.75000,0,0.01791,0.91529,0.67847,0.33333,0.16240,0.50000,0.00834,0.19118,0.00834,0.19643,0.20805,2,5,2
36350,36350,14260987,2.00000,4.00000,1361.00000,6059.00000,33.72950,-117.90591,7800.00000,47568.00000,1286.00000,97004.00000,1960.00000,62078.00000,382037.00000,319959.00000,4531.62000,Orange,57.00000,0.40000,1.18617,0.17906,0.20000,0.30000,45.61205,0.10000,41.02038,0.30000,0.50000,0,0.01791,0.26411,0.82471,0.16667,0.12013,0.50000,0.00987,0.41176,0.00987,0.10714,0.10550,4,2,3
24457,24457,14066920,2.50000,4.00000,1840.00000,6059.00000,33.71017,-118.02330,6305.00000,25218.00000,1286.00000,96967.00000,1965.00000,126210.00000,711616.00000,585406.00000,7920.96000,Orange,52.00000,0.40000,1.11309,0.14474,0.10000,0.40000,68.59239,0.20000,92.84790,0.40000,0.62500,0,0.01791,0.25097,0.76302,0.25000,0.11267,0.50000,0.00792,0.37500,0.00792,0.15179,0.15599,4,1,0
47718,47718,11236044,2.00000,3.00000,1244.00000,6037.00000,34.54453,-118.07068,7040.00000,40227.00000,3101.00000,97328.00000,1993.00000,114200.00000,199000.00000,84800.00000,3453.14000,Los_Angeles,24.00000,0.20000,1.73525,0.16162,0.20000,0.20000,91.80064,0.30000,12.04545,0.20000,0.66667,0,0.01791,0.81797,0.73812,0.16667,0.17619,0.33333,0.00888,0.16912,0.00888,0.16667,0.09317,2,1,2
46236,46236,11317435,3.00000,4.00000,2200.00000,6037.00000,34.68003,-118.24310,7759.00000,5534.00000,3101.00000,97319.00000,2005.00000,204300.00000,273000.00000,68700.00000,4280.00000,Los_Angeles,12.00000,0.13300,1.56777,0.17812,0.20000,0.50000,92.86364,0.30000,8.85423,0.20000,0.75000,0,0.01791,0.91005,0.64751,0.33333,0.15909,0.50000,0.00982,0.08088,0.00982,0.19643,0.19393,2,5,2

In [37]:

#validate_eval['ols_yhat'] = ols_model1.predict(X_validate)

Calculate Baseline RMSE

In [52]:

# Calculate and Add Residuals Column for Plotting
ols_eval['residuals'] = ols_eval.ols_yhat - ols_eval.actual
#validate_eval['residuals'] = validate_eval.ols_yhat - validate_eval.actual

In [59]:

#  Compute the RMSE  and R2 for  ols model and baseline 
baseline_RMSE = (sqrt(mean_squared_error(ols_eval.actual, ols_eval.baseline_yhat)))
ols_RMSE = (sqrt(mean_squared_error(ols_eval.actual, ols_eval.ols_yhat)))

In [60]:
baseline_RMSE

0.1747252013031296

In [61]:
ols_eval

        actual  baseline_yhat  ols_yhat  residuals
21580 -0.01503        0.01791   0.01352    0.02856
32781  0.15846        0.01791   0.03573   -0.12272
33161 -0.01774        0.01791   0.01181    0.02954
45785  0.06685        0.01791   0.01187   -0.05497
45820 -0.02213        0.01791   0.04110    0.06324
...        ...            ...       ...        ...
14404  0.03122        0.01791   0.04110    0.00988
1276   0.09111        0.01791   0.01591   -0.07520
34315 -0.01855        0.01791   0.01097    0.02952
24599  0.18463        0.01791   0.02338   -0.16125
14306 -0.02481        0.01791   0.01507    0.03988

[36384 rows x 4 columns]

In [54]:
baseline_RMSE

0

In [63]:

pct_change=round(((ols_RMSE-baseline_RMSE)/baseline_RMSE)*100, 2)
#rmse_validate = round(sqrt(mean_squared_error(validate_eval.actual, validate_eval.ols_yhat)))
baseline_r2 = (r2_score(ols_eval.actual, ols_eval.baseline_yhat), 2)
ols_train_r2 = (r2_score(ols_eval.actual, ols_eval.ols_yhat), 2)
#ols_validate_r2 = round(r2_score(validate_eval.actual, validate_eval.ols_yhat), 2)

#Output Findings

print(f'My model has value: {ols_RMSE < baseline_RMSE}')
print()
print(f'Baseline RMSE: {baseline_RMSE}')
print(f'My model train RMSE: {ols_RMSE}')
#print(f'My model validate RMSE: {rmse_validate}')
print(f'RMSE difference baseline to model: {baseline_RMSE- ols_RMSE}')
#print(f'RMSE difference train to validate: {ols_RMSE- rmse_validate}')
print(f'RMSE improvement: {pct_change}%')
print()
print(f'Baseline R2: {baseline_r2}')
print(f'Model train  R2: {ols_train_r2}')
#print(f'Model Validate R2: {ols_validate_r2}')

My model has value: True

Baseline RMSE: 0.1747252013031296
My model train RMSE: 0.17434797056175116
RMSE difference baseline to model: 0.00037723074137843704
RMSE improvement: -0.22%

Baseline R2: (0.0, 2)
Model train  R2: (0.004313327659981825, 2)

In [64]:
train.dtypes

Unnamed: 0                                int64
parcelid                                  int64
bathroomcnt                             float64
bedroomcnt                              float64
calculatedfinishedsquarefeet            float64
fips                                    float64
latitude                                float64
longitude                               float64
lotsizesquarefeet                       float64
regionidcity                            float64
regionidcounty                          float64
regionidzip                             float64
yearbuilt                               float64
structuretaxvaluedollarcnt              float64
taxvaluedollarcnt                       float64
landtaxvaluedollarcnt                   float64
taxamount                               float64
county                                   object
age                                     float64
age_bin                                 float64
taxrate                                 float64
acres                                   float64
acres_bin                               float64
sqft_bin                                float64
structure_dollar_per_sqft               float64
structure_dollar_sqft_bin               float64
land_dollar_per_sqft                    float64
lot_dollar_sqft_bin                     float64
bath_bed_ratio                          float64
cola                                      int64
logerror_bins                          category
baseline                                float64
scaled_latitude                         float64
scaled_longitude                        float64
scaled_bathroomcnt                      float64
scaled_taxrate                          float64
scaled_bedroomcnt                       float64
scaled_lotsizesquarefeet                float64
scaled_age                              float64
scaled_acres                            float64
scaled_bath_bed_ratio                   float64
scaled_calculatedfinishedsquarefeet     float64
area_cluster                             object
size_cluster                             object
price_cluster                            object
area_cluster_la_newer                     uint8
area_cluster_la_older                     uint8
area_cluster_northwest_costal             uint8
area_cluster_palmdale_landcaster          uint8
area_cluster_santa_clarita                uint8
area_cluster_se_coast                     uint8
size_cluster_a                            uint8
size_cluster_b                            uint8
size_cluster_c                            uint8
size_cluster_d                            uint8
size_cluster_e                            uint8
size_cluster_f                            uint8
size_cluster_g                            uint8
price_cluster_a                           uint8
price_cluster_b                           uint8
price_cluster_c                           uint8
price_cluster_d                           uint8
price_cluster_e                           uint8
log_error                               float64
mvp_prdictions                          float64
dtype: object

In [69]:
# Create Model
ols_model2 = ols(formula='log_error ~ area_cluster_la_newer + area_cluster_la_older + area_cluster_northwest_costal + area_cluster_palmdale_landcaster + area_cluster_santa_clarita + area_cluster_se_coast + bathroomcnt + bedroomcnt + calculatedfinishedsquarefeet + acres + age', data=train).fit()

# Make predictions
ols2_yhat = ols_model2.predict(X_train)
ols_eval['ols2_yhat']=ols2_yhat
X_train['ols2_prdictions']=ols2_yhat

In [70]:
ols_eval.head()

        actual  baseline_yhat  ols_yhat  residuals  ols2_yhat
21580 -0.01503        0.01791   0.01352    0.02856    0.01403
32781  0.15846        0.01791   0.03573   -0.12272    0.06059
33161 -0.01774        0.01791   0.01181    0.02954    0.00696
45785  0.06685        0.01791   0.01187   -0.05497    0.01460
45820 -0.02213        0.01791   0.04110    0.06324    0.03095

In [71]:
#Calculate Evaluation metrics
baseline_RMSE = (sqrt(mean_squared_error(ols_eval.actual, ols_eval.baseline_yhat)))
ols_RMSE = (sqrt(mean_squared_error(ols_eval.actual, ols_eval.ols_yhat)))
ols2_RMSE = (sqrt(mean_squared_error(ols_eval.actual, ols_eval.ols2_yhat)))
pct_change_baseline=(((ols_RMSE-baseline_RMSE)/baseline_RMSE)*100)
pct_change_last_model=(((ols2_RMSE-ols_RMSE)/ols_RMSE)*100)
#rmse_validate = (sqrt(mean_squared_error(validate_eval.actual, validate_eval.ols2_yhat)))
baseline_r2 = (r2_score(ols_eval.actual, ols_eval.baseline_yhat))
ols2_train_r2 = (r2_score(ols_eval.actual, ols_eval.ols2_yhat))
#ols2_validate_r2 = (r2_score(validate_eval.actual, validate_eval.ols2_yhat))
# Display findings
print(f'My model has value: {ols_RMSE < baseline_RMSE}')
print(f'My model beats previous model: {ols2_RMSE < ols_RMSE}')
print()
print(f'Baseline RMSE: {baseline_RMSE}')
print(f'Model 1 RMSE: {ols_RMSE}')
print(f'Currennt model train RMSE: {ols2_RMSE}')
#print(f'Currennt model validate RMSE: {rmse_validate}')
print()
print(f'Current model RMSE difference from baseline: {baseline_RMSE- ols_RMSE}')
#print(f'RMSE difference train to validate: {ols2_RMSE- rmse_validate}')
print(f'Current model baseline RMSE improvement: {pct_change_baseline}%')
print(f'Current model RMSE improvement from last model: {pct_change_last_model}%')
print()
print(f'Baseline R2: {baseline_r2}')
print(f'Model train  R2: {ols2_train_r2}')
#print(f'Model Validate R2: {ols2_validate_r2}')

My model has value: True
My model beats previous model: False

Baseline RMSE: 0.1747252013031296
Model 1 RMSE: 0.17434797056175116
Currennt model train RMSE: 0.17445037402983032

Current model RMSE difference from baseline: 0.00037723074137843704
Current model baseline RMSE improvement: -0.21589944585268034%
Current model RMSE improvement from last model: 0.058735107583537983%

Baseline R2: 0.0
Model train  R2: 0.0031433488903251927